[texte]
nicht_registiert = "User ist nicht registiert, Befehl !reg ausführen und Zustimmung erforderlich"

[texte.dia]
help = "Generiert ein Kuchendiagramm, gruppiert nach Allianzen. Ohne Zahlenparameter werden die letzten 60 Tage angezeigt. Oder man übergibt eine Zahl, dann werden die letzten x Tage angezeigt. all für Alles anzeigen"
brief = "Erstellt ein Kuchendiagramm"

[texte.uca]
help = "Abschüsse gruppiert nach Allianzen in Textform - Ohne Zahlenparameter werden die letzten 60 Tage angezeigt. Oder man übergibt eine Zahl, dann werden die letzten x Tage angezeigt. all für Alles anzeigen"
brief = "Abschüsse gruppiert nach Allianzen in Textform"

[texte.ucp]
help = "Abschüsse gelistet nach Angreifern, sortiert nach der Häufigkeit - Ohne Zahlenparameter werden die letzten 60 Tage angezeigt. Oder man übergibt eine Zahl, dann werden die letzten x Tage angezeigt. all für Alles anzeigen"
brief = "Abschüsse gelistet nach Angreifern"

[texte.uc]
help = """
Zum Eintragen der UC Mining Abschüsse im folgenden möglichen Format:
Datum(TT.MM.JJJJ) Allianztag Spielername
oder aber nur mit 2 Argumenten, dann wird das Datum automatisch eingetragen
Allianztag Spielername
Die Argumente sind immer durch ein Leerzeichen zu trennen. Allianztags werden immer alles in Großbuchstaben gespeichert.
Spielernamen werden immer komplett klein abgespeichert.
"""
brief = "Zum Eintragen der UC Mining Abschüsse"

[texte.reg]
help = """Holt die Zustimmung des Users zur Speicherung seiner Daten ein. Notwendig um den Bot benutzen zu können"""
brief = "Userregestrierung - notwendig um Bot verwenden zu können"
zustimmung_text = """
Beim Verwenden des Bots werden  die vom Benutzer gemachten Eintragungen in einer zum Bot zugehörigen Datenbank
gespeichert. Zusätzlich wird die eindeutige Discord User ID und der registrierte User Name (nicht der Anzeigename)
gespeichert.
Mit der Speicherung der oben genannten Daten bin ich ausdrücklich einverstanden!
Mir ist bewusst, dass auch weitere Daten wie in diesem Link
(https://discordpy.readthedocs.io/en/stable/api.html#discord.Member) zu meinem Account theoretisch erfasst werden
können.
Bist du mit den oben genannten Aufführungen einverstanden, so antworte dem Bot mit: ja ich stimme zu!
"""
zustimmung_antwort = "ja ich stimme zu!"

[texte.del]
help = "Löscht einen Registrierten User. All seine Einträge werden mit einem unbekannter User ersetzt"
brief = "Löschen der Zustimmung"
text = "Die Zustimmung wird gelöscht und alle Einträge werden durch einen unbekannten User ersetzt. Fortfahren? ja/nein"
antworten = ["ja", "nein"]

[bot_first_text]
text = """
**stfc_mining_shoots Bot**
**Welchen Zweck erfüllt der Bot?**
Der Bot nimmt UC Mining Abschüsse entgegen und erstellt darüber Statistiken und Grafiken, welche Spieler und Allianzen
die UC Abschüsse begehen.

**Befehlsübersicht**
del: Löschen der Zustimmung
dia:  Erstellt ein Kuchendiagramm
reg:  Userregestrierung - notwendig um Bot verwenden zu können
uc :  Zum Eintragen der UC Mining Abschüsse
uca: Abschüsse gruppiert nach Allianzen in Textform
ucp: Abschüsse gelistet nach Angreifern

Um die oben aufgeführten Befehle nutzen zu können muss ein ! davor gestellt werden.
Die Befehle werden in Discord mit dem Befehl !help angezeigt.
Eine Detailierte Hilfe in Discord wird mit dem Befehl '!help befehl' angzeigt.

**Vorgehensweise**
Damit der Bot genutzt werden kann muss zunächst der Registrierungsbefehl ausgeführt werden mit !reg und anschließend
eine Zustimmung erfolgen.
Anschließend ist es möglich Abschüsse einzutragen und Statistiken anzuzeigen.
Eintragungen werden vorgenommen mit dem Befehl:
!uc Allianztag Spielername
z.B:
!uc abc maxusternann

Die Statistiken können mit den Befehlen !uca, !ucp und !dia angezeigt werden.
Der Bot funktioniert nur im Kanal UC-Abschüsse.

*Dieser Kanal wird täglich um 12 Uhr geleert*

Viel Spaß mit dem Bot!"""